#!/bin/sh

set -Eueo pipefail

# The following is necessary to resolve symbolic links
pushd $(dirname $0)
GITHOOKS_DIR=`pwd -P`
popd
PROJECT_ROOT=`dirname $GITHOOKS_DIR`

set -x

npx webpack --env.production
git add $PROJECT_ROOT/assets/**/js/primer_spec_plugin.min.js
