#!/bin/sh
# Build a preview of the theme, only to be used in conjunction with
# Primer Spec Preview.
# NOTE: This file makes changes to _config.yml. Be careful when committing your
#       changes!

set -e

if [ "$#" != 2 ]; then
  echo "Usage: $0 URL BASE_URL"
  exit 1
fi
URL="$1"
BASE_URL="$2"

# Fix issue from jekyll/jekyll#2938
echo "exclude: [vendor]" >> _config.yml

# Update _config.yml URL
echo "url: $URL" >> _config.yml
echo "baseurl: $BASE_URL" >> _config.yml

# BUILD!
npx webpack --env.base_url="$URL$BASE_URL"
JEKYLL_ENV=site-preview bundle exec jekyll build
