#!/bin/sh
# Format the source files, or check them with script/prettier --check.

set -e

cd "$(dirname "$0")/.."
exec ./node_modules/.bin/prettier "src_js/**/*.{ts,tsx}" "_sass/spec/**/*.scss" "${1:---write}"
