#!/bin/sh
# Start the local preview server

set -e

rm -rf _site

# When the second command in the foreground is killed with Ctrl-c, the first
# command in the background is killed also.
# Based on https://unix.stackexchange.com/a/204619
trap 'kill %1' INT TERM
npx webpack --watch &
JEKYLL_ENV=dev bundle exec jekyll serve
# Finally, undo the trap.
trap - INT
